name: poo-01-intro
recipe: lamp
config:
  php: '7.4'
  webroot: .
  xdebug: 'develop,debug'
services:
  appserver:
    config:
      php: ./.lando.config/php.ini
  database:
    portforward: 3307
    creds:
      user: admin
      password: admin
      database: zenith